sudo: required
language: node_js
node_js:
- '8'
script:
- npm run lint:nofix

deploy:
  provider: script
  script: node ./scripts/deploy.js && ice-devtools generate && node ./scripts/generate-docs-database
  on:
    branch: ci/deploy
    repo: alibaba/ice
